### ISSUE TITLE
Not in sync at Packagist

### ISSUE THREAD

**Issue by stephandesouza** [electricjones/eloquent-meta#32]
@electricjones packgist stills on v.1.8.0 :(

https://packagist.org/packages/phoenix/eloquent-meta

**Comment by electricjones** [comment]
Thank you for pointing this out. I apparently had to do some update in composer. It is showing 1.9 for me now. Please confirm and I will close this issue.

**Comment by stephandesouza** [comment]
Its fine now, thanks. 👍
